# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bam_cpp <- function(bam_file, n_threads, min_mapq, include_unmapped, include_seq, include_qual, flag_require_set, flag_require_unset, tag_names_r, which_seqnames, which_starts, which_ends, which_labels, with_which_label, field_mask) {
    .Call(`_BamScale_read_bam_cpp`, bam_file, n_threads, min_mapq, include_unmapped, include_seq, include_qual, flag_require_set, flag_require_unset, tag_names_r, which_seqnames, which_starts, which_ends, which_labels, with_which_label, field_mask)
}

count_bam_cpp <- function(bam_file, n_threads, min_mapq, include_unmapped, flag_require_set, flag_require_unset, which_seqnames, which_starts, which_ends) {
    .Call(`_BamScale_count_bam_cpp`, bam_file, n_threads, min_mapq, include_unmapped, flag_require_set, flag_require_unset, which_seqnames, which_starts, which_ends)
}

